import { ROLES } from './roles.js';

export const PERMISSIONS = {
  // Donor
  VIEW_OWN_PROFILE: 'VIEW_OWN_PROFILE',
  UPDATE_OWN_PROFILE: 'UPDATE_OWN_PROFILE',
  VIEW_ELIGIBILITY: 'VIEW_ELIGIBILITY',
  RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',
  RESPOND_DONATION_REQUEST: 'RESPOND_DONATION_REQUEST',

  // Hospital
  CREATE_EMERGENCY_REQUEST: 'CREATE_EMERGENCY_REQUEST',
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  VIEW_MATCHED_DONORS: 'VIEW_MATCHED_DONORS',
  TRACK_REQUEST_STATUS: 'TRACK_REQUEST_STATUS',

  // Blood Bank
  UPDATE_INVENTORY: 'UPDATE_INVENTORY',
  VIEW_STOCK: 'VIEW_STOCK',
  MANAGE_EXPIRY: 'MANAGE_EXPIRY',
  RESPOND_HOSPITAL_REQUESTS: 'RESPOND_HOSPITAL_REQUESTS',

  // Admin
  MANAGE_USERS: 'MANAGE_USERS',
  APPROVE_DONORS: 'APPROVE_DONORS',
  UPDATE_DONOR_HEALTH: 'UPDATE_DONOR_HEALTH',
  VIEW_ALL_DATA: 'VIEW_ALL_DATA',
  OVERRIDE_SYSTEM: 'OVERRIDE_SYSTEM'
};

export const ROLE_PERMISSIONS = {
  [ROLES.DONOR]: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.UPDATE_OWN_PROFILE,
    PERMISSIONS.VIEW_ELIGIBILITY,
    PERMISSIONS.RECEIVE_NOTIFICATIONS,
    PERMISSIONS.RESPOND_DONATION_REQUEST
  ],

  [ROLES.HOSPITAL_STAFF]: [
    PERMISSIONS.CREATE_EMERGENCY_REQUEST,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_MATCHED_DONORS,
    PERMISSIONS.TRACK_REQUEST_STATUS
  ],

  [ROLES.BLOOD_BANK_STAFF]: [
    PERMISSIONS.UPDATE_INVENTORY,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.MANAGE_EXPIRY,
    PERMISSIONS.RESPOND_HOSPITAL_REQUESTS
  ],

  [ROLES.SYSTEM_ADMIN]: ['*'] // full access
};